/**
* Second Hand
* This is server to expose data for the second-hand marketplace application 
*
* OpenAPI spec version: 1.0.0
* Contact: rabhatt@syr.edu
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.server.models

import io.swagger.server.models.Item
import java.io.Serializable

/**
 * 
 * @param userIdsToIdsMap 
 */
data class GetItemsByUserIdsResponse (
    val userIdsToIdsMap: kotlin.collections.Map<kotlin.String, kotlin.Array<Item>>? = null
): Serializable {

}

