/**
* Second Hand
* This is server to expose data for the second-hand marketplace application 
*
* OpenAPI spec version: 1.0.0
* Contact: rabhatt@syr.edu
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.server.models


/**
 * 
 * @param name 
 * @param resourceType 
 * @param resourceLink 
 */
data class ItemResource (
    val name: kotlin.String? = null,
    val resourceType: ItemResource.ResourceType? = null,
    val resourceLink: kotlin.String? = null
) {

    /**
    * 
    * Values: iMAGE,vIDEO
    */
    enum class ResourceType(val value: kotlin.Any){
    
        IMAGE("IMAGE"),
    
        VIDEO("VIDEO");
    
    }

}

