/**
* Second Hand
* This is server to expose data for the second-hand marketplace application 
*
* OpenAPI spec version: 1.0.0
* Contact: rabhatt@syr.edu
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.server.models

/**
 * 
 * @param id 
 * @param name 
 * @param description 
 * @param category Item category
 * @param addedOn 
 * @param price 
 * @param soldInfo 
 * @param userId 
 * @param resources 
 */
data class Item (
    val id: kotlin.Long? = null,
    val name: kotlin.String? = null,
    val description: kotlin.String? = null,
    /* Item category */
    val category: kotlin.String? = null,
    val addedOn: String? = null,
    val price: kotlin.Float? = null,
    val soldInfo: SoldInfo? = null,
    val userId: kotlin.String? = null,
    val resources: kotlin.Array<ItemResource>? = null
) {

}

